### ISSUE TITLE
Git link cannot construct the remote url `Remote ‘origin’ not found`

### ISSUE THREAD

**Issue by yangchenyun** [sshaw/git-link#66] opened 2020-01-09 21:39 UTC
The `git config --get` has the proper URL for a remote:

```
git config --get remote.origin.url
git@github.com:grpc/grpc-web.git
```

But when invoked the `gitlink` command in emacs, it writes the error message:
`Remote ‘origin’ not found`

**Comment by sshaw** [comment] 2020-01-10 04:28
Tried with 0.7.4. Working. 

1. What version are you using? 
1. What the path of the file you're calling `git-link` on and is this an interactive invocation?
1. What's the path to the repository's root directory?

**Comment by sshaw** [comment] 2020-01-12 21:46
Closing to due to the inability for me to reproduce and lack of info. Feel free to reopen if you have more information.

**Closed by sshaw** 2020-01-12 21:46 UTC
